name: Build

on:
  push:
    branches:
      - main
      - gs14.5
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    name: Build (Java ${{ matrix.java-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile
        run: mvn -T 1C --batch-mode -Dstyle.color=always --fail-at-end -DskipTests package
      - name: Test
        run: mvn --batch-mode -Dstyle.color=always --fail-at-end verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
